// automatically generated by the FlatBuffers compiler, do not modify

package fb.risk;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class DayData extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static DayData getRootAsDayData(ByteBuffer _bb) { return getRootAsDayData(_bb, new DayData()); }
  public static DayData getRootAsDayData(ByteBuffer _bb, DayData obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public DayData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.risk.SymbolEntry symbols(int j) { return symbols(new fb.risk.SymbolEntry(), j); }
  public fb.risk.SymbolEntry symbols(fb.risk.SymbolEntry obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int symbolsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public fb.risk.SymbolEntry.Vector symbolsVector() { return symbolsVector(new fb.risk.SymbolEntry.Vector()); }
  public fb.risk.SymbolEntry.Vector symbolsVector(fb.risk.SymbolEntry.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createDayData(FlatBufferBuilder builder,
      int symbolsOffset) {
    builder.startTable(1);
    DayData.addSymbols(builder, symbolsOffset);
    return DayData.endDayData(builder);
  }

  public static void startDayData(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addSymbols(FlatBufferBuilder builder, int symbolsOffset) { builder.addOffset(0, symbolsOffset, 0); }
  public static int createSymbolsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startSymbolsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endDayData(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishDayDataBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedDayDataBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public DayData get(int j) { return get(new DayData(), j); }
    public DayData get(DayData obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

