package fb.risk;

import java.nio.file.Path;

public class FlatDBServerMain {

    public static void main(String[] args) throws Exception {
        // Path to your database generated by FlatDBWriter
        Path dbFile = Path.of("riskmodel.flatbuf");

        // Load memory-mapped file and build index
        FlatDBReader1 reader = new FlatDBReader1(dbFile);

        // Create gRPC server instance
        FlatDBGrpcServer server = new FlatDBGrpcServer(reader);

        // Start server on port 50051
        var grpcServer = server.start(50051);

        System.out.println("gRPC server started on port 50051");

        // Wait until termination
        grpcServer.awaitTermination();
    }
}

