// automatically generated by the FlatBuffers compiler, do not modify

package fb.risk;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class SymbolEntry extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_24_3_25(); }
  public static SymbolEntry getRootAsSymbolEntry(ByteBuffer _bb) { return getRootAsSymbolEntry(_bb, new SymbolEntry()); }
  public static SymbolEntry getRootAsSymbolEntry(ByteBuffer _bb, SymbolEntry obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SymbolEntry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public double factors(int j) { int o = __offset(6); return o != 0 ? bb.getDouble(__vector(o) + j * 8) : 0; }
  public int factorsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public DoubleVector factorsVector() { return factorsVector(new DoubleVector()); }
  public DoubleVector factorsVector(DoubleVector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer factorsAsByteBuffer() { return __vector_as_bytebuffer(6, 8); }
  public ByteBuffer factorsInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 8); }

  public static int createSymbolEntry(FlatBufferBuilder builder,
      int nameOffset,
      int factorsOffset) {
    builder.startTable(2);
    SymbolEntry.addFactors(builder, factorsOffset);
    SymbolEntry.addName(builder, nameOffset);
    return SymbolEntry.endSymbolEntry(builder);
  }

  public static void startSymbolEntry(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addFactors(FlatBufferBuilder builder, int factorsOffset) { builder.addOffset(1, factorsOffset, 0); }
  public static int createFactorsVector(FlatBufferBuilder builder, double[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addDouble(data[i]); return builder.endVector(); }
  public static void startFactorsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endSymbolEntry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SymbolEntry get(int j) { return get(new SymbolEntry(), j); }
    public SymbolEntry get(SymbolEntry obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

